[package]
name = "tauri-plugin-ios-google-oauth"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "tauri-plugin-ios-google-oauth"

[lib]
name = "tauri_plugin_ios_google_oauth"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2" }

[target.'cfg(target_os = "ios")'.dependencies]
tauri = { version = "2", features = ["wry"] }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
